name: Daily Pre-Market News Bot

on:
  schedule:
    - cron: '0 17 * * 1-5'  # 9:00 AM PST (5:00 PM UTC) Monday-Friday
  workflow_dispatch:

jobs:
  send-premarket-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pre-market news bot
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        python daily_news.py
